apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-management
  labels:
    app: notification-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-management
  template:
    metadata:
      labels:
        app: notification-management
    spec:
      containers:
        - name: notification-management
          image: "username/notification-management:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
